spring:
  config:
    import: aws-parameterstore:/config/member-card/

  cloud:
    aws:
      region:
        static: ap-northeast-2

  datasource:
    url: ${url}
    username: ${username}
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

cloud:
  aws:
    s3:
      bucket-name: ${s3-bucket-name}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  info:
    env:
      enabled: true

info:
  team-name: ${team-name}